CREATE TABLE tabulka_poslanci_euro (
    meno VARCHAR(255),
    priezvisko VARCHAR(255),
    web_source VARCHAR(255),
    email VARCHAR(255),
    strana VARCHAR(255),
    stat VARCHAR(255)
);

INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Magdalena', 'ADAMOWICZ', 'https://www.europarl.europa.eu/meps/sk/197490/MAGDALENA_ADAMOWICZ/home', 'magdalena.adamowicz@europarl.europa.eu', 'Poslanecký klub Európskej ľudovej strany (Kresťanských demokratov)', 'Poľsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Asim', 'ADEMOV', 'https://www.europarl.europa.eu/meps/sk/189525/ASIM_ADEMOV/home', 'asim.ademov@europarl.europa.eu', 'Poslanecký klub Európskej ľudovej strany (Kresťanských demokratov)', 'Bulharsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Isabella', 'ADINOLFI', 'https://www.europarl.europa.eu/meps/sk/124831/ISABELLA_ADINOLFI/home', 'isabella.adinolfi@europarl.europa.eu', 'Poslanecký klub Európskej ľudovej strany (Kresťanských demokratov)', 'Taliansko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Matteo', 'ADINOLFI', 'https://www.europarl.europa.eu/meps/sk/197826/MATTEO_ADINOLFI/home', 'matteo.adinolfi@europarl.europa.eu', 'Skupina Identita a demokracia', 'Taliansko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Alex', 'AGIUS, SALIBA', 'https://www.europarl.europa.eu/meps/sk/197403/ALEX_AGIUS+SALIBA/home', 'alex.agiussaliba@europarl.europa.eu', 'Skupina progresívnej aliancie socialistov a demokratov v Európskom parlamente', 'Malta');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Mazaly', 'AGUILAR', 'https://www.europarl.europa.eu/meps/sk/198096/MAZALY_AGUILAR/home', 'mazaly.aguilar@europarl.europa.eu', 'Európski konzervatívci a reformisti', 'Španielsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Clara', 'AGUILERA', 'https://www.europarl.europa.eu/meps/sk/125045/CLARA_AGUILERA/home', 'claraeugenia.aguileragarcia@europarl.europa.eu', 'Skupina progresívnej aliancie socialistov a demokratov v Európskom parlamente', 'Španielsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Alviina', 'ALAMETSÄ', 'https://www.europarl.europa.eu/meps/sk/204335/ALVIINA_ALAMETSA/home', 'alviina.alametsa@europarl.europa.eu', 'Skupina zelených/Európska slobodná aliancia', 'Fínsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('João', 'ALBUQUERQUE', 'https://www.europarl.europa.eu/meps/sk/237224/JOAO_ALBUQUERQUE/home', 'joao.albuquerque@europarl.europa.eu', 'Skupina progresívnej aliancie socialistov a demokratov v Európskom parlamente', 'Portugalsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Alexander', 'ALEXANDROV, YORDANOV', 'https://www.europarl.europa.eu/meps/sk/197836/ALEXANDER_ALEXANDROV+YORDANOV/home', 'alexander.yordanov@europarl.europa.eu', 'Poslanecký klub Európskej ľudovej strany (Kresťanských demokratov)', 'Bulharsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('François', 'ALFONSI', 'https://www.europarl.europa.eu/meps/sk/96750/FRANCOIS_ALFONSI/home', 'francois.alfonsi@europarl.europa.eu', 'Skupina zelených/Európska slobodná aliancia', 'Francúzsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Atidzhe', 'ALIEVA-VELI', 'https://www.europarl.europa.eu/meps/sk/197848/ATIDZHE_ALIEVA-VELI/home', 'atidzhe.alieva-veli@europarl.europa.eu', 'skupina Renew Europe', 'Bulharsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Abir', 'AL-SAHLANI', 'https://www.europarl.europa.eu/meps/sk/197400/ABIR_AL-SAHLANI/home', 'abir.alsahlani@europarl.europa.eu', 'skupina Renew Europe', 'Švédsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Catherine', 'AMALRIC', 'https://www.europarl.europa.eu/meps/sk/247122/CATHERINE_AMALRIC/home', 'catherine.amalric@europarl.europa.eu', 'skupina Renew Europe', 'Francúzsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Andris', 'AMERIKS', 'https://www.europarl.europa.eu/meps/sk/197783/ANDRIS_AMERIKS/home', 'andris.ameriks@europarl.europa.eu', 'Skupina progresívnej aliancie socialistov a demokratov v Európskom parlamente', 'Lotyšsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Christine', 'ANDERSON', 'https://www.europarl.europa.eu/meps/sk/197475/CHRISTINE_ANDERSON/home', 'christine.anderson@europarl.europa.eu', 'Skupina Identita a demokracia', 'Nemecko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Rasmus', 'ANDRESEN', 'https://www.europarl.europa.eu/meps/sk/197448/RASMUS_ANDRESEN/home', 'rasmus.andresen@europarl.europa.eu', 'Skupina zelených/Európska slobodná aliancia', 'Nemecko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Barry', 'ANDREWS', 'https://www.europarl.europa.eu/meps/sk/204332/BARRY_ANDREWS/home', 'barry.andrews@europarl.europa.eu', 'skupina Renew Europe', 'Írsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Mathilde', 'ANDROUËT', 'https://www.europarl.europa.eu/meps/sk/197691/MATHILDE_ANDROUET/home', 'mathilde.androuet@europarl.europa.eu', 'Skupina Identita a demokracia', 'Francúzsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Marc', 'ANGEL', 'https://www.europarl.europa.eu/meps/sk/202073/MARC_ANGEL/home', 'marc.angel@europarl.europa.eu', 'Skupina progresívnej aliancie socialistov a demokratov v Európskom parlamente', 'Luxembursko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Gerolf', 'ANNEMANS', 'https://www.europarl.europa.eu/meps/sk/124973/GEROLF_ANNEMANS/home', 'gerolf.annemans@europarl.europa.eu', 'Skupina Identita a demokracia', 'Belgicko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Andrus', 'ANSIP', 'https://www.europarl.europa.eu/meps/sk/124696/ANDRUS_ANSIP/home', 'andrus.ansip@europarl.europa.eu', 'skupina Renew Europe', 'Estónsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Attila', 'ARA-KOVÁCS', 'https://www.europarl.europa.eu/meps/sk/197587/ATTILA_ARA-KOVACS/home', 'attila.ara-kovacs@europarl.europa.eu', 'Skupina progresívnej aliancie socialistov a demokratov v Európskom parlamente', 'Maďarsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Maria', 'ARENA', 'https://www.europarl.europa.eu/meps/sk/124936/MARIA_ARENA/home', 'maria.arena@europarl.europa.eu', 'Skupina progresívnej aliancie socialistov a demokratov v Európskom parlamente', 'Belgicko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Pablo', 'ARIAS, ECHEVERRÍA', 'https://www.europarl.europa.eu/meps/sk/96808/PABLO_ARIAS+ECHEVERRIA/home', 'pablo.ariasecheverria@europarl.europa.eu', 'Poslanecký klub Európskej ľudovej strany (Kresťanských demokratov)', 'Španielsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Pascal', 'ARIMONT', 'https://www.europarl.europa.eu/meps/sk/24922/PASCAL_ARIMONT/home', 'pascal.arimont@europarl.europa.eu', 'Poslanecký klub Európskej ľudovej strany (Kresťanských demokratov)', 'Belgicko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Konstantinos', 'ARVANITIS', 'https://www.europarl.europa.eu/meps/sk/197701/KONSTANTINOS_ARVANITIS/home', 'kostas.arvanitissyriza@gmail.com', 'Skupina ľavice v Európskom parlamente - GUE/NGL', 'Grécko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Anna-Michelle', 'ASIMAKOPOULOU', 'https://www.europarl.europa.eu/meps/sk/197695/ANNA-MICHELLE_ASIMAKOPOULOU/home', 'anna-misel.asimakopoulou@europarl.europa.eu', 'Poslanecký klub Európskej ľudovej strany (Kresťanských demokratov)', 'Grécko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Manon', 'AUBRY', 'https://www.europarl.europa.eu/meps/sk/197533/MANON_AUBRY/home', 'manon.aubry@europarl.europa.eu', 'Skupina ľavice v Európskom parlamente - GUE/NGL', 'Francúzsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Margrete', 'AUKEN', 'https://www.europarl.europa.eu/meps/sk/28161/MARGRETE_AUKEN/home', 'margrete.auken@europarl.europa.eu', 'Skupina zelených/Európska slobodná aliancia', 'Dánsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Petras', 'AUŠTREVIČIUS', 'https://www.europarl.europa.eu/meps/sk/124766/PETRAS_AUSTREVICIUS/home', 'petras.austrevicius@europarl.europa.eu', 'skupina Renew Europe', 'Litva');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Carmen', 'AVRAM', 'https://www.europarl.europa.eu/meps/sk/197651/CARMEN_AVRAM/home', 'carmen-gabriela.avram@europarl.europa.eu', 'Skupina progresívnej aliancie socialistov a demokratov v Európskom parlamente', 'Rumunsko');
INSERT INTO tabulka_poslanci_euro (meno, priezvisko, web_source, email, strana, stat) VALUES ('Malik', 'AZMANI', 'https://www.europarl.europa.eu/meps/sk/197781/MALIK_AZMANI/home', 'malik.azmani@europarl.europa.eu', 'skupina Renew Europe', 'Holandsko');